apiVersion: v2
name: swednabler
description: A Parent Helm chart for swednabler
type: application
version: 0.1.0
dependencies:
  - name: aperta
    repository: file://charts/aperta
    version: 1.0.0
    condition: aperta.enabled
  - name: curat
    repository: file://charts/curat
    version: 1.0.0
    condition: curat.enabled
  - name: simplex
    repository: file://charts/simplex
    version: 1.0.0
    condition: simplex.enabled