apiVersion: v1
kind: Service
metadata:
  name: {{ include "curat.fullname" . }}
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: {{- include "curat.selectorLabels" . | nindent 4 }}