# This job runs when changes are merged to master branch. It will build, test and push images to dockerhub.
name: swednabler-build-test-push-image-on-master
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        service: [ "aperta", "curat", "simplex" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.0'

      - name: Build service
        run: cd ${{ matrix.service }} && go build -v ./...

      - name: Test service
        run: cd ${{ matrix.service }}  && go test -v ./...

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: tenhaus/get-release-or-tag@v2
        id: tag

      - name: Build and push to Dockerhub
        id: id_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.service }}
          tags: |
            chetanketh/${{ matrix.service }}:${{ steps.tag.outputs.tag }}
            chetanketh/${{ matrix.service }}:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: echo ${{ steps.id_build.outputs.digest }}